### ISSUE TITLE
Factional War seems to not provide a timer

### ISSUE THREAD

**Issue by SfSec** [Shadowrabbit/ModRimWorldFactionalWar#8]
When finishing a factional war, there is no timer to say when the map will close. 
This then causes the player to lose all the associated pawns in the map when it decides to randomly close the map.

Can you please provide a timer for after finishing all the remaining enemies on the map, how long until the map closes please?

I'm recently playing this on rim together but its frankly frustrating because I can't give you logs on that because im not the host. And the previous instance this happened in singleplayer mode I simply chose to reload the game from an earlier save or use development mode where necessary to fix my issue. 

I can't do that in a multiplayer rimworld so I have to ask you to implement a timer.

**Comment by SfSec** [comment]
Actually nvm, I found a way to review logs, and it was cause a pawn died from a shot to the heart + another fell asleep with sleeping sickness. I'ma close issue.

**Comment by Shadowrabbit** [comment]
I'm sorry the design wasn't meticulous enough back then. Have fun!


Shadowrabbit
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shadowrabbit/FactionalWar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月9日(星期二) 中午1:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Shadowrabbit/FactionalWar] Factional War seems to not provide a timer (Issue #8)





 
Actually nvm, I found a way to review logs, and it was cause a pawn died from a shot to the heart + another fell asleep with sleeping sickness. I'ma close issue.
